# Name: Akshay Jain

# Student ID: A20502846

# Course Number: CS512

# Semester: Spring 22

# Solution A

In [46]:
#importing required libraries and defining a,b,c
import math
import numpy as np
from numpy.linalg import eig

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
c = np.array([[-1], [1], [3]])

In [47]:
#1
print("value of 2*a-b is:")
2*a-b

value of 2*a-b is:


array([[-2],
       [-1],
       [ 0]])

In [48]:
#2
print("a unit vector in direction of a:")
a_hat = a / (a**2).sum()**0.5
a_hat

a unit vector in direction of a:


array([[0.26726124],
       [0.53452248],
       [0.80178373]])

In [49]:
#3.a
mag_of_a =np.linalg.norm(a)
print('||a|| is :', mag_of_a)

||a|| is : 3.7416573867739413


In [50]:
#3.b
# 'X' a vector corresponding to +ve X axis
X = np.array([[1], [0], [0]])

X_sqz = np.squeeze(np.asarray(X))
a_hat_sqz = np.squeeze(np.asarray(a_hat))

dot_product = np.dot(a_hat_sqz, X_sqz)

relative_angle = np.arccos(dot_product)
relative_angle_in_degrees= np.degrees(relative_angle)
print ("angle (in degrees) of vector 'a' realtive to positive X axis is :",relative_angle_in_degrees)

angle (in degrees) of vector 'a' realtive to positive X axis is : 74.498640433063


In [51]:
#4
cosa= a_hat[0]
cosb= a_hat[1]
cosc= a_hat[2]
print("direction cosines of a :", cosa, cosb, cosc)

direction cosines of a : [0.26726124] [0.53452248] [0.80178373]


In [52]:
#5
unit_vector_a = a / np.linalg.norm(a)
unit_vector_b = b / np.linalg.norm(b)

a1 = np.squeeze(np.asarray(unit_vector_a))
b1 = np.squeeze(np.asarray(unit_vector_b))

dot_product = np.dot(a1, b1)

angle = np.arccos(dot_product)
angle_in_degrees= np.degrees(angle)

print("angle between a and b :",angle_in_degrees)

angle between a and b : 12.933154491899135


In [53]:
#6
asqz = np.squeeze(np.asarray(a))
bsqz = np.squeeze(np.asarray(b))
adotb = np.dot(asqz, bsqz)
bdota = np.dot(bsqz, asqz)
print("a.b :",adotb)
print("b.a :",bdota)

a.b : 32
b.a : 32


In [54]:
#7
# using value of angle from answer 5
adotb = np.linalg.norm(a)* np.linalg.norm(b)*math.cos(angle)
print("a.b by using angle b/w a and b: is", adotb) 

a.b by using angle b/w a and b: is 32.0


In [55]:
#8 ## Scaler projection ?
b_sqz = np.squeeze(np.asarray(b))
projection_value = np.dot(b_sqz, a_hat) / np.linalg.norm(a_hat_sqz)
print(("projection of b onto a_hat is :"), projection_value)

projection of b onto a_hat is : [8.55235974]


In [56]:
#9
a_cross_b = np.cross(a, b, axis=0)
print("a vector perpendiculat to vector 'a' is :",a_cross_b)

a vector perpendiculat to vector 'a' is : [[-3]
 [ 6]
 [-3]]


In [57]:
#10
# Note : for cross product vectors are defined along the first axis, rather than the last axis.
a_cross_b = np.cross(a, b, axis=0)
b_cross_a = np.cross(b, a, axis=0)

print("cross product a x b is:",a_cross_b)
print("cross product b x a is:",b_cross_a)

cross product a x b is: [[-3]
 [ 6]
 [-3]]
cross product b x a is: [[ 3]
 [-6]
 [ 3]]


In [58]:
#11
print("a vector which is perpendiculat to both vector 'a' and 'b' is :",a_cross_b)

a vector which is perpendiculat to both vector 'a' and 'b' is : [[-3]
 [ 6]
 [-3]]


In [59]:
#12 #CHECK
M = np.array([[1, 4, -1], 
    [2,5,1],
    [3,6,3]])

determinant = np.linalg.det(M)
print("determinant of a,b,c is", round(determinant,3))
print("as the determinant of a,b,c is '0.0', vectors are Not Linearly Dependent")

determinant of a,b,c is 0.0
as the determinant of a,b,c is '0.0', vectors are Not Linearly Dependent


In [8]:
#13
a_transpose = a.transpose()
b_transpose = b.transpose()
print("a_transpose*b : ",a_transpose@b)
print("b_transpose*a : ",a@b_transpose)

a_transpose*b :  [[32]]
b_transpose*a :  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Solution B

In [29]:
# defining a,b,c,d
A = np.array([[1, 2, 3], 
    [4,-2, 3],
    [0,5,-1]])
B = np.array([[1, 2, 1], 
    [2,1,-4],
    [3,-2,1]])
C= np.array([[1, 2, 3], 
    [4,5,6],
    [-1,1,3]])
d = np.array([[1], [2], [3]])

In [30]:
#1
print("2*A-B:")
2*A-B

2*A-B:


array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

In [31]:
#2
AB = A @ B # using @ operator
BA = B @ A
print("matrix multiplication AB:",AB)
print("matrix multiplication BA:",BA)

matrix multiplication AB: [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
matrix multiplication BA: [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [32]:
#3
transpose_AB = AB.transpose() # using AB from answer 2

transpose_A = A.transpose()
transpose_B = B.transpose()
transpose_B_transpose_A = transpose_B @ transpose_A

print("transpose_AB", transpose_AB)
print("transpose_B_transpose_A", transpose_B_transpose_A)

transpose_AB [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
transpose_B_transpose_A [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [33]:
#4
print('|A| is:', round(np.linalg.det(A),4))
print('|C| is:', round(np.linalg.det(C),4))

|A| is: 55.0
|C| is: 0.0


In [34]:
#5
print("'B' is the only matrix in which row vectors form an orthogonal set as the dot product of the rows is zero")

'B' is the only matrix in which row vectors form an orthogonal set as the dot product of the rows is zero


In [35]:
#6
inverse_of_matrix_A = np.linalg.inv(A)
inverse_of_matrix_B = np.linalg.inv(B)
print("inverse_of_matrix_A is :",inverse_of_matrix_A)
print("inverse_of_matrix_B is :",inverse_of_matrix_B)

inverse_of_matrix_A is : [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
inverse_of_matrix_B is : [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [36]:
#7
inverse_of_matrix_C = np.linalg.inv(C)
print("inverse_of_matrix_C is :",inverse_of_matrix_C)

inverse_of_matrix_C is : [[ 1.20095990e+16 -4.00319967e+15 -4.00319967e+15]
 [-2.40191980e+16  8.00639934e+15  8.00639934e+15]
 [ 1.20095990e+16 -4.00319967e+15 -4.00319967e+15]]


In [37]:
#8
Ad = A @ d
print("matrix multiplication Ad:",Ad)

matrix multiplication Ad: [[14]
 [ 9]
 [ 7]]


In [43]:
#9
scaler_projection = np.dot(A, d) / np.linalg.norm(d)
print("scaler_projection of A onto d :", scaler_projection)

scaler_projection of A onto d : [[3.74165739]
 [2.40535118]
 [1.87082869]]


In [44]:
#10
vector_projection = (np.dot(A, d) / np.linalg.norm(d)**2 ) * d
print("vector_projection of A onto d :", scaler_projection)

vector_projection of A onto d : [[3.74165739]
 [2.40535118]
 [1.87082869]]


In [ ]:
#11

In [41]:
#12

In [ ]:
#13

# Solution C

In [11]:
# defining D,E,F
D = np.array([[1, 2], 
    [3, 2]])
E = np.array([[2, -2], 
    [-2, 5]])
F = np.array([[1,2], 
    [2,4]])

In [74]:
#1
w,v=eig(D)
print('eigenvalues of D:', w)
print('corresponding eigenvectors of D', v)

eigenvalues of D: [-1.  4.]
corresponding eigenvectors of D [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [76]:
#2
print("dot product b/w eigenvectors of D")
dot_product = np.dot(v[0], v[1])
dot_product #check

dot product b/w eigenvectors of D


-0.038461538461538214

In [77]:
#3
w,v=eig(E)
print("dot product b/w eigenvectors of E")
dot_product = np.dot(v[0], v[1])
dot_product

dot product b/w eigenvectors of E


0.0

In [9]:
#4
print(" from answer 3 as dot product of eigen vectors of E is zero so one of the property is both the eigen vectors are perpendiculat to each other ")

 from answer 3 as dot product of eigen vectors of E is zero so one of the property is both the eigen vectors are perpendiculat to each other 


In [25]:
#5
print('|F| is:', round(np.linalg.det(F),4))
print("as the determinant of F is '0' therfore only trivial solution for F(x) is (0,0)")

|F| is: 0.0
as the determinant of F is '0' therfore only trivial solution for F(x) is (0,0)


In [27]:
#6
print('|F| is:', round(np.linalg.det(F),4))
print("non-trivial solution of F(x)=0 is x = -2y" )

|F| is: 0.0
non-trivial solution of F(x)=0 is x = -2y


In [60]:
#7 #check
print('|D| is:', round(np.linalg.det(D),4))
print('On solving D matrix we get x+2y=0 and 3x+2y=0, hence the only possible outcome for x and y is (0,0)')

|D| is: -4.0
On solving D matrix we get x+2y=0 and 3x+2y=0, hence the only possible outcome for x and y is (0,0)
