In [27]:
import numpy as np
import pandas as pd

In [251]:
world_pt = np.loadtxt("world_points.txt")
world_pt[:, 2] =1 ## for planar caliberation
#print(world_pt)

In [252]:
world_pt.shape, img1.shape

((121, 3), (121, 2))

In [294]:
img1 = np.loadtxt("image1.txt")
img2 = np.loadtxt("image2.txt")
img3 = np.loadtxt("image3.txt")

In [295]:
img2.shape, img3.shape

((121, 2), (121, 2))

In [297]:
# for img1
x = img1[:,0]
y= img1[:,1]
XP = []
for i in range(len(world_pt)):
    a = (x[i]*world_pt[i])
    XP.append(a)
YP = []
for i in range(len(world_pt)):
    a = (y[i]*world_pt[i])
    YP.append(a)

In [298]:
M = np.empty((9))
for i in range(len(world_pt)):
    a = world_pt[i]
    b = -XP[i]
    c = -YP[i]
    row1 = [a[0],a[1],a[2], 0,0,0, b[0],b[1],b[2]]
    row2 = [0,0,0, a[0],a[1],a[2],c[0],c[1],c[2]]
    d = np.vstack([row1,row2])
    #print(M.shape)
    M = np.vstack([M,d])
M

array([[ 3.00000000e+02,  3.00000000e+02,  1.00000000e+00, ...,
        -1.26100320e+05, -1.26100320e+05, -4.20334400e+02],
       [ 1.00000000e+02,  1.00000000e+02,  1.00000000e+00, ...,
        -2.43273700e+04, -2.43273700e+04, -2.43273700e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -6.84347000e+03, -6.84347000e+03, -6.84347000e+01],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.34181540e+05, -1.25236104e+05, -4.47271800e+02],
       [ 3.00000000e+02,  3.00000000e+02,  1.00000000e+00, ...,
        -1.26100320e+05, -1.26100320e+05, -4.20334400e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.39306380e+05, -1.39306380e+05, -4.64354600e+02]])

In [311]:
len(M),len(M2),len(M3)

(243, 243, 243)

In [299]:
# for img2
x2 = img2[:,0]
y2 = img2[:,1]
XP2 = []
for i in range(len(world_pt)):
    a = (x2[i]*world_pt[i])
    XP2.append(a)
YP2 = []
for i in range(len(world_pt)):
    a = (y2[i]*world_pt[i])
    YP2.append(a)

In [300]:
M2 = np.empty((9))
for i in range(len(world_pt)):
    a = world_pt[i]
    b = -XP2[i]
    c = -YP2[i]
    row1 = [a[0],a[1],a[2], 0,0,0, b[0],b[1],b[2]]
    row2 = [0,0,0, a[0],a[1],a[2],c[0],c[1],c[2]]
    d = np.vstack([row1,row2])
    #print(M.shape)
    M2 = np.vstack([M2,d])
M2

array([[ 3.00000000e+02,  3.00000000e+02,  1.00000000e+00, ...,
        -1.26100320e+05, -1.26100320e+05, -4.20334400e+02],
       [ 1.00000000e+02,  1.00000000e+02,  1.00000000e+00, ...,
        -2.85200400e+04, -2.85200400e+04, -2.85200400e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -8.78261000e+03, -8.78261000e+03, -8.78261000e+01],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.29903990e+05, -1.21243724e+05, -4.33013300e+02],
       [ 3.00000000e+02,  3.00000000e+02,  1.00000000e+00, ...,
        -1.10738640e+05, -1.10738640e+05, -3.69128800e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.36450140e+05, -1.36450140e+05, -4.54833800e+02]])

In [301]:
# for img3
x3 = img2[:,0]
y3 = img2[:,1]
XP3 = []
for i in range(len(world_pt)):
    a = (x3[i]*world_pt[i])
    XP3.append(a)
YP3 = []
for i in range(len(world_pt)):
    a = (y3[i]*world_pt[i])
    YP3.append(a)

In [302]:
M3 = np.empty((9))
for i in range(len(world_pt)):
    a = world_pt[i]
    b = -XP3[i]
    c = -YP3[i]
    row1 = [a[0],a[1],a[2], 0,0,0, b[0],b[1],b[2]]
    row2 = [0,0,0, a[0],a[1],a[2],c[0],c[1],c[2]]
    d = np.vstack([row1,row2])
    #print(M.shape)
    M3 = np.vstack([M3,d])
M3

array([[ 3.00000000e+02,  3.00000000e+02,  1.00000000e+00, ...,
        -1.10738640e+05, -1.10738640e+05, -3.69128800e+02],
       [ 1.00000000e+02,  1.00000000e+02,  1.00000000e+00, ...,
        -2.85200400e+04, -2.85200400e+04, -2.85200400e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -8.78261000e+03, -8.78261000e+03, -8.78261000e+01],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.29903990e+05, -1.21243724e+05, -4.33013300e+02],
       [ 3.00000000e+02,  3.00000000e+02,  1.00000000e+00, ...,
        -1.10738640e+05, -1.10738640e+05, -3.69128800e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.36450140e+05, -1.36450140e+05, -4.54833800e+02]])

In [303]:
# for img1
u,d,v_t = np.linalg.svd(M)
v = np.transpose(v_t)
v

array([[-1.02154651e-03, -7.61895192e-04,  4.95863216e-01,
        -5.64013515e-01,  4.33940771e-01,  3.61346711e-01,
         3.42211413e-01, -4.43610179e-04, -4.68139181e-03],
       [-1.18705681e-03,  1.45295211e-03,  4.45597827e-01,
        -2.42752396e-01, -1.41219581e-01, -1.58581028e-02,
        -8.49846447e-01,  5.91027527e-03,  6.47806801e-03],
       [-5.10193891e-06,  2.33088930e-06,  2.22150157e-03,
        -2.93339706e-03, -7.80327501e-04, -1.50528952e-03,
         6.92132140e-03, -3.44405022e-01,  9.38786909e-01],
       [-9.21841063e-04, -2.89976596e-03, -5.05931636e-01,
        -2.36590385e-01, -2.39031144e-01,  7.75344466e-01,
        -1.72380946e-01,  4.41500596e-03,  4.39307992e-03],
       [-8.86275992e-04, -9.36830937e-04, -5.47060084e-01,
        -5.07879391e-01,  4.76640414e-01, -4.12445822e-01,
        -2.13235267e-01,  3.22192479e-03,  2.19653972e-03],
       [-4.02987037e-06, -8.80412948e-06, -2.50653189e-03,
        -2.85934724e-03, -6.29453069e-05,  2.614918

In [304]:
# for img2
u2,d2,v2_t = np.linalg.svd(M2)
v2 = np.transpose(v2_t)
v2

array([[-1.01664722e-03, -1.03068553e-03,  5.03030996e-01,
        -5.50645448e-01,  4.55020797e-01,  2.69393469e-01,
         4.05103583e-01, -1.59576030e-03,  4.36865216e-03],
       [-1.20488226e-03,  1.16348915e-03,  4.55810271e-01,
        -2.07862503e-01, -1.05129204e-01,  1.68379958e-01,
        -8.42359702e-01,  6.21048297e-03, -3.86955126e-03],
       [-5.19542672e-06,  9.89441568e-07,  2.26421720e-03,
        -2.80777175e-03, -7.24520807e-04, -1.60928152e-03,
         5.71280068e-03, -7.52195897e-02, -9.97142544e-01],
       [-9.29429328e-04, -3.10074964e-03, -4.99150887e-01,
        -2.34827108e-01, -1.89656281e-01,  8.11798095e-01,
        -2.61699666e-02,  4.37172505e-03, -2.12425824e-03],
       [-9.19185391e-04, -1.10627641e-03, -5.38072026e-01,
        -4.97818839e-01,  4.82256344e-01, -3.71973375e-01,
        -3.02818847e-01,  3.95376225e-03, -1.60326681e-03],
       [-4.13879810e-06, -9.51536110e-06, -2.47032706e-03,
        -2.90342821e-03,  1.17431478e-04,  2.985720

In [305]:
# for img3
u3,d3,v3_t = np.linalg.svd(M3)
v3 = np.transpose(v3_t)
v3

array([[-1.01702979e-03, -1.03232958e-03,  5.03895005e-01,
        -5.52533311e-01,  4.51387240e-01,  2.68042653e-01,
         4.06418383e-01, -1.47690600e-03,  4.39047457e-03],
       [-1.20591546e-03,  1.16169718e-03,  4.56603690e-01,
        -2.05497415e-01, -1.04461621e-01,  1.70858394e-01,
        -8.42094439e-01,  6.10491584e-03, -3.99294826e-03],
       [-5.20276828e-06,  9.73532073e-07,  2.26829687e-03,
        -2.79661898e-03, -7.45262813e-04, -1.62828103e-03,
         5.67998593e-03, -9.83582714e-02, -9.95126733e-01],
       [-9.32492667e-04, -3.10902831e-03, -4.98335288e-01,
        -2.32856067e-01, -1.89059082e-01,  8.13044081e-01,
        -2.49289564e-02,  4.35429216e-03, -2.24293359e-03],
       [-9.22235953e-04, -1.11340208e-03, -5.37318853e-01,
        -5.02199987e-01,  4.78753423e-01, -3.71176126e-01,
        -3.03458294e-01,  3.90015250e-03, -1.68219993e-03],
       [-4.15248527e-06, -9.54990190e-06, -2.46651528e-03,
        -2.91789679e-03,  9.83784152e-05,  3.039813

In [313]:
# for img1
lcol = v[:,-1]
h_11 = np.transpose([np.array(lcol[0:3])])
h_12 = np.transpose([np.array(lcol[3:6])])
h_13 = np.transpose([np.array(lcol[6:9])])
H_img1 = np.hstack([h_11,h_12,h_13])
H_img1

array([[-4.68139181e-03,  4.39307992e-03, -3.60589418e-06],
       [ 6.47806801e-03,  2.19653972e-03, -1.80294823e-06],
       [ 9.38786909e-01, -3.44332297e-01,  5.13840020e-03]])

In [314]:
# for img2
lcol2 = v2[:,-1]
h_21 = np.transpose([np.array(lcol2[0:3])])
h_22 = np.transpose([np.array(lcol2[3:6])])
h_23 = np.transpose([np.array(lcol2[6:9])])
H_img2 = np.hstack([h_21,h_22,h_23])
H_img2

array([[ 4.36865216e-03, -2.12425824e-03,  3.01267849e-06],
       [-3.86955126e-03, -1.60326681e-03,  2.21668785e-06],
       [-9.97142544e-01,  7.51719020e-02, -3.84596136e-03]])

In [315]:
# for img3
lcol3 = v3[:,-1]
h_31 = np.transpose([np.array(lcol3[0:3])])
h_32 = np.transpose([np.array(lcol3[3:6])])
h_33 = np.transpose([np.array(lcol3[6:9])])
H_img3 = np.hstack([h_31,h_32,h_33])
H_img3

array([[ 4.39047457e-03, -2.24293359e-03,  2.79152714e-06],
       [-3.99294826e-03, -1.68219993e-03,  2.09364606e-06],
       [-9.95126733e-01,  9.83105863e-02, -3.83835176e-03]])

In [354]:
#Vij for img1
def fnvij(h,i,j):
    h=h.T
    a = np.array([h[i-1][0]*h[j-1][0], h[i-1][0]*h[j-1][1] + h[i-1][1]*h[j-1][0], h[i-1][1]*h[j-1][1], h[i-1][2]*h[j-1][0]+ h[i-1][0]*h[j-1][2], 
     h[i-1][2]*h[j-1][1]+ h[i-1][1]*h[j-1][2], h[i-1][2]*h[j-1][2]])
    #vij = np.transpose(a)
    return a

In [441]:
# for H_img1
Tv12_1 = fnvij(H_img1,1,2)
Tv11_1 = fnvij(H_img1,1,1)
Tv22_1 =fnvij(H_img1,2,2)
d_1 = Tv11_1 - Tv22_1

In [442]:
# for H_img2
Tv12_2 = fnvij(H_img2,1,2)
Tv11_2 = fnvij(H_img2,1,1)
Tv22_2 =fnvij(H_img2,2,2)
d_2 = Tv11_2 - Tv22_2

In [443]:
# for H_img3
Tv12_3 = fnvij(H_img3,1,2)
Tv11_3 = fnvij(H_img3,1,1)
Tv22_3 =fnvij(H_img3,2,2)
d_3 = Tv11_3 - Tv22_3

In [444]:
V = np.vstack([Tv12_1,d_1,Tv12_2,d_2,Tv12_3,d_3])

In [445]:
V

array([[-2.05657283e-05,  1.81758074e-05,  1.42293337e-05,
         5.73612031e-03, -1.68525305e-04, -3.23254653e-01],
       [ 2.61627814e-06, -7.99518981e-05,  3.71405784e-05,
        -5.76430010e-03,  1.36757300e-02,  7.62756131e-01],
       [-9.28014532e-06,  1.21581111e-06,  6.20392312e-06,
         2.44658815e-03,  1.30780402e-03, -7.49571016e-02],
       [ 1.45726486e-05, -4.06209524e-05,  1.24029625e-05,
        -8.39296878e-03,  7.95802960e-03,  9.88642437e-01],
       [-9.84754289e-06,  1.57026177e-06,  6.71693727e-06,
         2.66363330e-03,  1.28145303e-03, -9.78314926e-02],
       [ 1.42455159e-05, -4.26080010e-05,  1.31138392e-05,
        -8.29714901e-03,  8.27773524e-03,  9.80612244e-01]])

In [446]:
V.shape

(6, 6)

In [447]:
## SVD
u,d,v_t = np.linalg.svd(V)
v = np.transpose(v_t)
v

array([[ 1.46468842e-05,  2.25591130e-03,  3.70893718e-03,
         2.93223419e-01, -1.52709116e-01, -9.43759030e-01],
       [-5.64420570e-05,  4.03533273e-03, -9.23121161e-03,
        -2.61124929e-01, -9.62368254e-01,  7.45628099e-02],
       [ 1.80748188e-05, -3.95863957e-03, -6.30836447e-04,
        -9.19677450e-01,  2.24575666e-01, -3.22091740e-01],
       [-8.75850729e-03, -3.67192051e-01, -9.30064698e-01,
         4.98612300e-03,  5.72629805e-03, -3.91036513e-03],
       [ 9.93955656e-03, -9.30105692e-01,  3.67071028e-01,
         1.52426152e-03, -7.76170981e-03,  9.48956260e-04],
       [ 9.99912241e-01,  6.02957929e-03, -1.17961008e-02,
         2.61125683e-05,  7.11675268e-05, -1.98295487e-05]])

In [448]:
lcol = v[:,-1]

In [449]:
lcol

array([-9.43759030e-01,  7.45628099e-02, -3.22091740e-01, -3.91036513e-03,
        9.48956260e-04, -1.98295487e-05])

In [450]:
s11 = lcol[0]
s12 = lcol[1]
s22 = lcol[2]
s13 = lcol[3]
s23= lcol[4]
s33 = lcol[5]

In [451]:
#parameters
c1 = s11*s13 -s11*s23
c2 = s11*s22 -s12*s12
v_ =c1/c2
lambdha = s33 - (s13*s13 + v_*c1)/s11
au =np.sqrt(lambdha/s11)
av = np.sqrt(lambdha/c2)
s = -(s12*(au*au)*av)/lambdha
u0 = (s*v_/au) - (s13*(au*au)/lambdha)

/var/folders/t9/xrpzmpls0hx9zn2fc6byfjh80000gn/T/ipykernel_60366/2190177057.py:6: RuntimeWarning: invalid value encountered in sqrt
  au =np.sqrt(lambdha/s11)


In [452]:
c1,c2,v_,lambdha,au,av,s,u0

(0.004586028438236496,
 0.2984173751743656,
 0.015367833175118823,
 7.104987356080968e-05,
 nan,
 0.01543013059052545,
 nan,
 nan)

In [453]:
K_star = [[au, s, u0], [0, av, v_], [0, 0, 1]]

#K_star_inv = np.linalg.inv(K_star)

# T_star = alpha * K_star_inv* h3

# r1 = alpha* K_star_inv* h1
# r2 = alpha* K_star_inv* h2
# r3 = np.cross(r1, r2)

In [454]:
K_star

[[nan, nan, nan], [0, 0.01543013059052545, 0.015367833175118823], [0, 0, 1]]